import type { Metadata } from "next";

import "@/assets/scss/index.scss";
import { roboto, montserrat } from "@/assets/fonts";
import "@fortawesome/fontawesome-svg-core/styles.css";

import Header from "@/components/Header/Header";
import { availableLanguages } from "@/utils/i18n";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return availableLanguages.map((lang) => ({ lang }));
}

export default function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${montserrat.variable}`}>
        <Header lang={lang} />
        <main>{children}</main>
      </body>
    </html>
  );
}
